# Generated by Django 6.0 on 2025-12-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_late_submission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='extra_time',
            field=models.PositiveIntegerField(default=0, help_text='Extra time in minutes'),
        ),
    ]
